### ISSUE TITLE
How to fix this? TypeError: __init__() missing 1 required positional argument: 'dtype'

### ISSUE THREAD

**Issue by Fisher-Wang** [guanyingc/PS-FCN#16]
I'm interested in your research and tried to run the code, but encountered the following error, could you help me to fix it? Thanks!

#### How to reproduce
I wanted to test PS-FCN on DiLiGenT main dataset using all of the 96 image-light pairs by running
`CUDA_VISIBLE_DEVICES=0 python eval/run_model.py --retrain data/models/PS-FCN_B_S_32.pth.tar --in_img_num 96 --cuda`
with arg `--cuda` added since my computer has no GPU

#### Current Behavior
```
------------ Options -------------
        benchmark: DiLiGenT_main
        bm_dir: data/datasets/DiLiGenT/pmsData
        cuda: False
        epochs: 30
        fuse_type: max
        in_img_num: 96
        in_light: True
        item: calib
        log_dir: data/models\run_model
        model: PS_FCN_run
        normalize: False
        resume: None
        retrain: data/models/PS-FCN_B_S_32.pth.tar
        run_model: True
        save_root: data/Training/
        seed: 0
        start_epoch: 1
        test_batch: 1
        test_disp: 1
        test_intv: 1
        test_save: 1
        time_sync: False
        train_img_num: 32
        use_BN: False
        workers: 8
-------------- End ----------------

=> fetching img pairs in data/DiLiGenT_main
[test Data]     10 objs 96 lights. Root: data/datasets/DiLiGenT/pmsData
Files for intensity: light_intensities.txt
         Found Benchmark Data: 10 samples
         Test Batch 1
Creating Model PS_FCN_run
[Network Input] Color image as input
[Network Input] Adding Light direction as input
[Network Input] Input channel: 6
Conv pad = 1
Conv pad = 1
Conv pad = 1
Conv pad = 1
Conv pad = 1
Conv pad = 1
Conv pad = 1
Conv pad = 1
=> using pre-trained model data/models/PS-FCN_B_S_32.pth.tar
PS_FCN(
  (extractor): FeatExtractor(
    (conv1): Sequential(
      (0): Conv2d(6, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (conv2): Sequential(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (conv3): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (conv4): Sequential(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (conv5): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (conv6): Sequential(
      (0): ConvTranspose2d(256, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (conv7): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
  )
  (regressor): Regressor(
    (deconv1): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (deconv2): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (deconv3): Sequential(
      (0): ConvTranspose2d(128, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
      (1): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (est_normal): Sequential(
      (0): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    )
  )
)
=> Model Parameters: 2210048
---- Start test Epoch 1: 10 batches ----
Traceback (most recent call last):
  File "eval/run_model.py", line 23, in <module>
    main(args)
  File "eval/run_model.py", line 19, in main
    test_utils.test(args, 'test', test_loader, model, log, 1, recorder)
  File ".\test_utils.py", line 21, in test
    for i, sample in enumerate(loader):
  File "C:\Users\Fisher\miniconda3\envs\cv\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\Fisher\miniconda3\envs\cv\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\Users\Fisher\miniconda3\envs\cv\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\Users\Fisher\miniconda3\envs\cv\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtype'
```

#### My working environment
- Win10
- no GPU or CUDA
- torch 1.7.1+cpu
- torchvision 0.8.2+cpu

BTW, I don't understand why the required PyTorch version is 1.10, since the latest version on pytorch.org is 1.8. Do you mean 0.1.10?

**Comment by guanyingc** [comment]
Hi, please kindly use an older version of Pytorch. Sorry for the typo. We use v1.1.0. For example, installing using the following command.
```
 conda install pytorch==1.1.0 torchvision==0.3.0 -c pytorch
```

**Comment by Fisher-Wang** [comment]
Thanks!
I installed PyTorch v1.2.0 and torchvision v0.4.2 by 
```shell
pip install https://download.pytorch.org/whl/cpu/torchvision-0.4.2%2Bcpu-cp37-cp37m-win_amd64.whl
```
```shell
```

**Comment by Fisher-Wang** [comment]
Thanks! 
With PyTorch v1.2.0+cpu and torchvision v0.4.2+cpu installed, I run the test successfully. 
```shell
pip install https://download.pytorch.org/whl/cpu/torchvision-0.4.2%2Bcpu-cp37-cp37m-win_amd64.whl
pip install https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp37-cp37m-win_amd64.whl
CUDA_VISIBLE_DEVICES=0 python eval/run_model.py --retrain data/models/PS-FCN_B_S_32.pth.tar --in_img_num 96 --cuda
```
BTW, it took about half an hour to run the test on my cpu.
